# Generated by Django 4.0.4 on 2022-06-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
