# Generated by Django 4.0.4 on 2022-06-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0003_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
