# Generated by Django 4.0.4 on 2022-06-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0006_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
